// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Services;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    partial class ContactsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool>("Married")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1980, 1, 1),
                            Married = true,
                            Name = "John Doe",
                            Phone = "+380563829166",
                            Salary = 1000m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1985, 1, 1),
                            Married = false,
                            Name = "Jane Doe",
                            Phone = "+380594629166",
                            Salary = 2000m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Married = true,
                            Name = "Sammy Doe",
                            Phone = "+380563829166",
                            Salary = 3000m
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(1995, 1, 1),
                            Married = false,
                            Name = "Sally Doe",
                            Phone = "+380888829166",
                            Salary = 4000m
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateOnly(2000, 1, 1),
                            Married = true,
                            Name = "Sandy Doe",
                            Phone = "+380563829166",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateOnly(2005, 1, 1),
                            Married = false,
                            Name = "Victor Van",
                            Phone = "+380563800566",
                            Salary = 6000m
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateOnly(2010, 1, 1),
                            Married = true,
                            Name = "Maria Red",
                            Phone = "+380568837666",
                            Salary = 7000m
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateOnly(2015, 1, 1),
                            Married = false,
                            Name = "Pan Cat",
                            Phone = "+380563826694",
                            Salary = 8000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
